name: Atlas
on: [push, pull_request]

jobs:
  test:
    name: Atlas Tests
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        node-version: [12.x]
      fail-fast: true
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{matrix.node-version}}
        uses: actions/setup-node@v1
        with:
          node-version: ${{matrix.node-version}}
      - name: Install modules
        run: yarn install --frozen-lockfile
      - name: Run Tests
        run: yarn coverage
  lint:
    name: Atlas Lint
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        node-version: [12.x]
      fail-fast: true
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{matrix.node-version}}
        uses: actions/setup-node@v1
        with:
          node-version: ${{matrix.node-version}}
      - name: Install root modules
        run: yarn install --frozen-lockfile
      - name: Install modules
        run: yarn install --frozen-lockfile
      - name: Run ESLint
        run: yarn lint
